config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :recommendations do
    member do
      get "accept_first_match"
      get "accept_second_match"
      get "decline"
    end
  end

  resources :comments
  resources :users do
    resources :profiles
  end
  resources :profiles
  resources :friendships
  resources :received_recommendations
  resources :accepted_recommendations
  resources :accepted_recommendations do
    member do
      post "create_comment"
    end
  end

  get 'users/recommended_as_match' => 'users#recommendedasmatch', :as => :recommended_as_match

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TickleTush</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body class="site">


                  <ul class="navigation">
                          <li>
                            <strong><a href="/">TickleTush</a></strong>
                          </li>
                          <li>

                          <% if current_user %>
                          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
                          <% else %>
                          <!-- <a href='/users/sign_in'>Sign In</a> -->
                          </li>
                          <li>
                            <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
                          </li>
                          <% end %>


                          <% if current_user %>
                          <li>
                            <a href="/users/show">Profile</a>
                          </li>
                          <% end %>
                          <% if current_user %>
                          <li>
                            <a href='/users'>Play Matchmaker</a>
                          </li>
                          <% end %>
                          <% if current_user %>
                          <li>
                            <%= link_to "Matches I've Made", recommendation_path(current_user) %>
                          </li>
                          <% end %>
                          <% if current_user %>
                          <li>
                            <%= link_to "My Pending Matches", received_recommendations_path %>
                          </li>
                          <% end %>
                          <% if current_user %>
                          <li>
                            <%= link_to "My Accepted Matches", accepted_recommendations_path %>
                          </li>
                          <% end %>
                      </ul>
      <main class="site-content">
        <%= yield %>
      </main>

      <footer class="site-footer">
        TickleTush! Copyright 2015
        <img src="">
      </footer>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
<!--jQuery and Bootstrap js-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</body>
</html>